export const state = {
  db:                     null,
  auth:                   null,
  session:                null,
  combatantManager:       null,
  tracker:                null,
  myUid:                  null,
  myCombatantId:          null,
  myCurrentCharId:        null,
  snapshot:               null,
  sheet:                  null,
  sheetData:              null,
  acMap:                  {},
  lastKnownHp:            null,
  library:                null,
  selectedJoinCharId:     null,
  selectedCreatureCharId: null,
  sheetReturnView:        'view-combat',
  selectedGridTokenId:    null,
};
